In [1]:
import numpy as np
test = np.array([1,2,3])
test
test2 = np.array([[1,2,3],[4,5,6]])
test2
test3 = np.array([1,2,3,4,5], ndmin=2)
test3

array([[1, 2, 3, 4, 5]])

In [14]:
test.shape
test2.shape
test3.shape

(1, 5)

In [19]:
test4 = np.array([[1,2,3],[4,5,6]])
test4.shape #(2,3)
test4

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
test5 = test4.reshape(3,2)
test5 #(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
test6 = np.arange(10)
test6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
test6[0]
test6[:5]
test6[-1]
test6[1:-1]
test6[1:]
test6.shape

(10,)

In [48]:
test7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
test7.shape
test7[0]
test7[2]
test7[1:]
test7[1:,1]
test7[:,[0,2]] # [rows, cols]
# 1,2,3
# 4,5,6
# 7,8,9

array([[1, 3],
       [4, 6],
       [7, 9]])

In [54]:
test8 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.amin(test8) #1
np.amin(test8, 1)
np.amin(test8, 0)

array([1, 2, 3])

In [55]:
np.amax(test8)

9

In [56]:
np.ptp(test8) # min ~ max

8

In [57]:
np.percentile(test8,50)

5.0

In [58]:
np.percentile(test8, 50, 1)

array([2., 5., 8.])

In [59]:
np.percentile(test8, 50, 0)

array([4., 5., 6.])

In [61]:
# 1,1,1,1,3,4,7,7,7,7,10 
np.median(test8)

5.0

In [62]:
np.mean(test8)

5.0

In [66]:
np.average(test8)

5.0

In [67]:
np.std(test8)

2.581988897471611

In [68]:
data = [1,2,3,4]
np.mean(data)
# 1.5 0.5...

2.5

In [69]:
np.std(data)

1.118033988749895

In [71]:
np.var(data)

1.25

In [72]:
import statistics
test_data = [5,2,5,6,1,1,2,5,7,8]

In [73]:
statistics.mean(test_data)

4.2

In [74]:
statistics.median(test_data)

5.0

In [75]:
statistics.stdev(test_data)

2.5298221281347035

In [76]:
statistics.variance(test_data)

6.4

In [77]:
statistics.mode(test_data)

5